name:           TestSimple
version:        0.2.1

ghc-options: -Wall
description: 
    version 0.2.1 - no imports, no test, to learn about ghcide
dependencies:
  - base == 4.*
#   - uniform-strings
#   - uniform-convenience
# #  - test-framework 
#   - QuickCheck
#   - HTF

library:
  source-dirs: .

executables:
  foo:
    main: ClassMain.hs
    source-dirs: src
    dependencies: 
      - TestSimple

# tests:
#   test1:
#     main: ExampleTesting.hs
#     source-dirs: tests
#     dependencies: 
#       - TestSimple
# #      - QuickCheck 
# #      - test-framework 

